replicaCount: 1

image:
  repository: ghcr.io/al-gorceries-2/al-gorceries-2-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

ingress:
  enabled: true
  host: api.al-gorceries.com
  path: /
  tls:
    enabled: true
    secretName: api-al-gorceries-com-tls

global:
  postgresql:
    auth:
      username: al-gorceries-2
      database: al-gorceries-2
      password: al-gorceries-2
