replicaCount: 2

image:
  repository: ghcr.io/al-gorceries-2/al-gorceries-2-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: api.al-gorceries.com
  annotations:
    kubernetes.io/ingress.class: traefik

env:
  SPRING_DATASOURCE_URL: jdbc:postgresql://al-gorceries-2-postgresql:5432/postgres
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres

postgresql:
  enabled: true
  global:
    postgresqlUsername: postgres
    postgresqlPassword: postgres
    postgresqlDatabase: postgres
  persistence:
    enabled: true
    size: 1Gi
