apiVersion: apps/v1
kind: Deployment
metadata:
  name: al-gorceries-2-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: al-gorceries-2-api
  template:
    metadata:
      labels:
        app: al-gorceries-2-api
    spec:
      containers:
        - name: al-gorceries-2-api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.SPRING_DATASOURCE_URL }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.env.SPRING_DATASOURCE_USERNAME }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.env.SPRING_DATASOURCE_PASSWORD }}
