apiVersion: v1
kind: Service
metadata:
  name: al-gorceries-2-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: backend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
